@Library('Shared') _

pipeline {
    agent any

    environment {
        GIT_URL          = "https://github.com/rupesh-hub/FitVerse-2026-01-01.git"
        GIT_BRANCH       = "main"
        PROJECT_PATH     = "frontend"
        DOCKERFILE_PATH  = "../docker/frontend/Dockerfile"
        DOCKERHUB_REPO   = "rupesh1997/fitverse-frontend"
        SONAR_API_ENV    = "SonarQube"
    }

    stages {
        stage("Workspace Cleanup") {
            steps { cleanWs() }
        }

        stage('Checkout & Versioning') {
            steps {
                script {
                    checkoutRepository(env.GIT_URL, env.GIT_BRANCH)
                    env.APP_VERSION = getVersion(env.PROJECT_PATH)
                    echo "Frontend Version identified: ${env.APP_VERSION}"
                }
            }
        }

        stage('Security & Build') {
            parallel {
                stage('Sonar & Audit') {
                    steps {
                        dir("${env.PROJECT_PATH}") {
                            script {
                                // Install deps for Sonar to work correctly
                                npmExecute('install', '.')
                                sonarScan(projectName: "fitverse-frontend", projectKey: "fitverse-frontend-key", apiEnv: env.SONAR_API_ENV)
                                npmExecute('audit --audit-level=high', '.')
                            }
                        }
                    }
                }
                stage('Trivy FS Scan') {
                    steps { trivyFsScan(env.PROJECT_PATH) }
                }
            }
        }

        stage("Docker: Build & Push") {
            steps {
                dir("${env.PROJECT_PATH}") {
                    script {
                        def tags = ["latest", env.APP_VERSION]
                        // Passing the CONFIGURATION build-arg as requested
                        def buildParams = [
                            'PROJECT_VERSION': env.APP_VERSION,
                            'CONFIGURATION'  : 'production'
                        ]

                        dockerBuild(env.DOCKERHUB_REPO, tags, buildParams, env.DOCKERFILE_PATH)
                        trivyScan(["${env.DOCKERHUB_REPO}:${env.APP_VERSION}"])
                        pushImages(["${env.DOCKERHUB_REPO}:latest", "${env.DOCKERHUB_REPO}:${env.APP_VERSION}"], "dockerhub")
                    }
                }
            }
        }
    }

    post {
        success {
            script {
                notify('SUCCESS', 'dulalrupesh77@gmail.com')
                // Trigger the CD job with SERVICE_NAME parameter
                build job: "FitVerse-CD", parameters: [
                    string(name: 'DOCKER_TAG', value: env.APP_VERSION),
                    string(name: 'SERVICE_NAME', value: 'frontend')
                ]
            }
        }
        failure {
            script { notify('FAILURE', 'dulalrupesh77@gmail.com') }
        }
    }
}