@Library('Shared') _

pipeline {
    agent any

    tools {
        jdk 'Java17'
        maven 'maven-3'
        nodejs 'node-20'
    }

    /*parameters {
        booleanParam(name: 'RUN_SECURITY_SCANS', defaultValue: true, description: 'Run Trivy and Sonar scans?')
    }*/

    environment {
        GIT_URL                   = "https://github.com/rupesh-hub/FitVerse-2026-01-01.git"
        GIT_BRANCH                = "main"
        DOCKERHUB_CRED_ID         = "dockerhub" // The ID of your Jenkins Docker credentials

        // Backend Config
        BE_PATH                   = "backend"
        BE_DOCKERFILE             = "docker/backend/Dockerfile"
        BE_REPO                   = "rupesh1997/fitverse-backend"

        // Frontend Config
        FE_PATH                   = "frontend"
        FE_DOCKERFILE             = "docker/frontend/Dockerfile"
        FE_REPO                   = "rupesh1997/fitverse-frontend"

        ACTIVE_PROFILE            = "production"
    }

    stages {
        stage("Workspace Cleanup") {
            steps {
                cleanWs()
            }
        }

        stage('Checkout & Versioning') {
            steps {
                script {
                    checkoutRepository(env.GIT_URL, env.GIT_BRANCH)
                    // Extract versions for both
                    env.BE_VERSION = getVersion(env.BE_PATH)
                    env.FE_VERSION = getVersion(env.FE_PATH)
                    echo "Backend: ${env.BE_VERSION} | Frontend: ${env.FE_VERSION}"
                }
            }
        }

        stage('Parallel Build & Scan') {
            parallel {
                stage('Backend Build') {
                    steps {
                        script {
                            mavenExecute('clean package', env.BE_PATH)
                            /*if (params.RUN_SECURITY_SCANS) { */
                            trivyFsScan(env.BE_PATH)
                            /*}*/
                        }
                    }
                }

                stage('Frontend Build') {
                    steps {
                        dir("${env.FE_PATH}") {
                            script {
                               nodejs('node-20') {
                                    npmExecute('install', ".")
                                    /*if (params.RUN_SECURITY_SCANS) { */
                                        // npmExecute('audit --audit-level=high', '.')
                                        trivyFsScan(".")
                                    /* } */
                               }
                            }
                        }
                    }
                }
            }
        }

        stage('Docker Productionization') {
            parallel {
                stage('Backend Image') {
                    steps {
                        script {
                            def tags = ["latest", env.BE_VERSION]
                            def buildArgs = ['PROJECT_VERSION': env.BE_VERSION, 'ACTIVE_PROFILE': env.ACTIVE_PROFILE]

                            dockerBuild(env.BE_REPO, tags, buildArgs, env.BE_DOCKERFILE)

                            if (params.RUN_SECURITY_SCANS) {
                                trivyImageScan(["${env.BE_REPO}:${env.BE_VERSION}"])
                            }
                            pushImages(["${env.BE_REPO}:latest", "${env.BE_REPO}:${env.BE_VERSION}"], env.DOCKERHUB_CRED_ID)
                        }
                    }
                }

                stage('Frontend Image') {
                    steps {
                        script {
                            def tags = ["latest", env.FE_VERSION]
                            def buildArgs = ['PROJECT_VERSION': env.FE_VERSION, 'CONFIGURATION': 'production']

                            dockerBuild(env.FE_REPO, tags, buildArgs, env.FE_DOCKERFILE)

                            if (params.RUN_SECURITY_SCANS) {
                                trivyImageScan(["${env.FE_REPO}:${env.FE_VERSION}"])
                            }
                            pushImages(["${env.FE_REPO}:latest", "${env.FE_REPO}:${env.FE_VERSION}"], env.DOCKERHUB_CRED_ID)
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            script {
                notify('SUCCESS', 'dulalrupesh77@gmail.com')

                // Trigger the single CD Job with both tags
                echo "Triggering CD Pipeline for FitVerse Release..."
                build job: "FitVerse-CD", parameters: [
                    string(name: 'BACKEND_IMAGE_TAG', value: env.BE_VERSION),
                    string(name: 'FRONTEND_IMAGE_TAG', value: env.FE_VERSION)
                ]
            }
        }
        failure {
            script {
                notify('FAILURE', 'dulalrupesh77@gmail.com')
            }
        }
    }
}