pipeline {
    agent any

    environment {
        DOCKER_HUB_CREDENTIALS_ID = 'docker-hub-credentials'
        DOCKER_REPO = 'rupesh1997'
        PROJECT_VERSION = ''
    }

    stages {

        stage("Cleanup Workspace") {
            steps {
                deleteDir()
                echo "Workspace cleaned successfully."
            }
        }

        stage("Checkout repository") {
            steps {
                git url: 'https://github.com/rupesh-hub/FirVerse.git', branch: 'main'
            }
        }

        stage("Extract project version") {
            steps {
                dir('backend') {
                    script {
                        env.PROJECT_VERSION = sh(
                            script: """
                                ./mvnw help:evaluate \
                                -Dexpression=project.version \
                                -q -DforceStdout
                            """,
                            returnStdout: true
                        ).trim()
                    }
                }
                echo "✔ Extracted project version: ${env.PROJECT_VERSION}"
            }
        }

        stage("Build & Test") {
            parallel {
                stage("Build") {
                    steps {
                        dir('backend') {
                            sh "./mvnw clean package -DskipTests"
                        }
                    }
                }

                stage("Unit tests") {
                    steps {
                        dir('backend') {
                            sh "./mvnw test"
                        }
                        junit '**/target/surefire-reports/TEST-*.xml'
                    }
                }
            }
        }

        stage("Build Docker Image") {
            steps {
                echo "Building Docker image..."
                sh """
                    docker build \
                      -t ${DOCKER_REPO}/fit-verse-backend:${PROJECT_VERSION} \
                      -t ${DOCKER_REPO}/fit-verse-backend:latest \
                      -f docker/backend/Dockerfile .
                """
            }
        }

        stage("Trivy Vulnerability Scan") {
            steps {
                echo "🔍 Running Trivy image scan..."
                sh """
                    trivy image --exit-code 0 \
                        --severity HIGH,CRITICAL \
                        ${DOCKER_REPO}/fit-verse-backend:${PROJECT_VERSION}
                """
            }
        }

        stage("Docker Hub Login") {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: env.DOCKER_HUB_CREDENTIALS_ID,
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASSWORD'
                )]) {
                    sh "echo '${DOCKER_PASSWORD}' | docker login -u ${DOCKER_USER} --password-stdin"
                }
            }
        }

        stage("Push Docker Images") {
            steps {
                sh "docker push ${DOCKER_REPO}/fit-verse-backend:${PROJECT_VERSION}"
                sh "docker push ${DOCKER_REPO}/fit-verse-backend:latest"
            }
        }

        stage("Deployment") {
            steps {
                echo "🚀 Deploying application..."
                sh """
                    docker-compose -f docker/docker-compose/production/docker-compose.yaml pull
                    docker-compose -f docker/docker-compose/production/docker-compose.yaml down --remove-orphans
                    docker-compose -f docker/docker-compose/production/docker-compose.yaml up -d
                    docker container prune -f
                """
            }
        }
    }

    post {
        always {
            echo "Cleaning workspace..."
            cleanWs()
        }
        success {
            echo "🎉 Pipeline executed successfully!"
        }
        failure {
            echo "❌ Pipeline failed. Please check logs."
        }
    }
}
