@Library('Shared') _

pipeline {
    agent any

    parameters {
        string(name: 'DOCKER_TAG', defaultValue: '', description: 'Tag passed from CI Job')
        string(name: 'SERVICE_NAME', defaultValue: 'backend', description: 'backend or frontend')
    }

    environment {
        GIT_URL          = "https://github.com/rupesh-hub/FitVerse-2026-01-01.git"
        GIT_BRANCH       = "main"
        DOCKERHUB_USER   = "rupesh1997"
        GIT_CRED_ID      = "git-ssh-cred"
    }

    stages {
        stage('Checkout Manifests') {
            steps {
                // Checkout the root directory (FitVerse)
                checkoutRepo(env.GIT_URL, env.GIT_BRANCH, env.GIT_CRED_ID)
            }
        }

        stage('Update Manifests') {
            steps {
                script {
                    if (!params.DOCKER_TAG) {
                        error "DOCKER_TAG is required. CD aborted."
                    }

                    // Updates Compose, K8s yaml, and helm/values.yaml in Git
                    updateManifests(
                        serviceName: params.SERVICE_NAME,
                        version: params.DOCKER_TAG,
                        dockerUser: env.DOCKERHUB_USER
                    )
                }
            }
        }

        stage('Deploy: Docker Compose') {
            steps {
                script {
                    echo "Deploying via Docker Compose..."
                    dir("docker/docker-compose/production") {
                        sh "docker compose pull"
                        sh "docker compose up -d"
                    }
                }
            }
        }

        stage('Deploy: Helm (Kubernetes)') {
            steps {
                script {
                    // Uses the Helm folder in the root directory
                    helmDeploy(
                        releaseName: 'fitverse-backend',
                        chartPath:   './helm',
                        version:     params.DOCKER_TAG,
                        namespace:   'production'
                    )
                }
            }
        }
    }

    post {
        success {
            notify('SUCCESS', 'dev-ops@example.com')
        }
        failure {
            notify('FAILURE', 'dev-ops@example.com')
        }
        always {
            cleanWs()
        }
    }
}